# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

# Name of the service configuration.
name: $$ENDPOINT_NAME$$

endpoints:
  - name: $$ENDPOINT_NAME$$
    target: "$$STATIC_IP_ADDRESS$$"

# API title to appear in the user interface (Google Cloud Console).
title: Cobalt Report Master gRPC API
apis:
- name: cobalt.analyzer.ReportMaster

usage:
  rules:
  # All methods can be called without an API Key.
  - selector: "*"
    allow_unregistered_calls: true

authentication:
  providers:
  - id: google_auth
    issuer: https://accounts.google.com
    # This is the OAuth 2.0 Client ID for the report_client application. It is
    # registered with Google and it is hard-coded into the report_client's Go
    # code.
    audiences: 915138408459-535q0s4l88eppnidvidhlcdvavdcgtfq.apps.googleusercontent.com
  rules:
    - selector: "*"
      allow_without_credential: false
      oauth:
        canonical_scopes: https://www.googleapis.com/auth/userinfo.email
      requirements:
        - provider_id: google_auth
