# Copyright 2016 The Fuchsia Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file contans the definitions of the Shuffler's  Deployment object
# (which includes an embedded defintion of the Shuffler's Pod object) and the
# Shuffler's Service object.
#
# The definitions contain some parameters (indicated by $$PARAMETER_NAME$$)
# that will be replaced by the script tools/container_util.py prior to being
# passed to "kubectl create"

# The defintion of the Deployment and Pod
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shuffler
  labels:
    name: shuffler
# Pod object
spec:
  replicas: 1
  template:
    metadata:
      name: shuffler
      labels:
        name: shuffler
    spec:
      containers:
      - name: endpoint
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          '-P', '8000',
          '-S', '443',
          '-s', '$$ENDPOINT_NAME$$',
          '-v', '$$ENDPOINT_CONFIG_ID$$',
          '-a', 'grpc://127.0.0.1:5000'
          ]
        ports:
          - containerPort: 8000
          - containerPort: 443
        volumeMounts:
          - mountPath: /etc/nginx/ssl
            # The name must match the volumes.name for
            # shuffler-certificate-storage.
            name: shuffler-certificate-storage
            readOnly: true
      - name: shuffler
        # The URI of a Docker image in a Docker repository.
        image: $$SHUFFLER_IMAGE_URI$$
        args:
          - '-port'
          - '5000'
          - '-analyzer_uri'
          # This must match the defintion of the "analyzer-service" Service
          # in analyzer_service_deployment.yaml
          - 'analyzer-service:6001'
          - '-config_file'
          # This is the path to where the file is copied in Dockerfile.
          -  '/etc/cobalt/shuffler_config.txt'
          - '-db_dir'
          # This path must match mountPath for shuffler-persistent-storage
          # below.
          - '/var/lib/cobalt/db'
          - '-use_memstore=$$SHUFFLER_USE_MEMSTORE$$'
          - '-private_key_pem_file'
          # The directory path must match mountPath for shuffler-key-storage
          # below.
          - '/var/lib/cobalt/key/$$SHUFFLER_PRIVATE_PEM_NAME$$'
          - '-danger_danger_delete_all_data_at_startup=$$DANGER_DANGER_DELETE_ALL_DATA_AT_STARTUP$$'
          # TODO(rudominer) Eventually remove this.
          - '-logtostderr'
          - '-v=3'
        ports:
          - containerPort: 5000
        volumeMounts:
            # This name must match the volumes.name for
            # shuffler-persistent-storage below.
          - name: shuffler-persistent-storage
            mountPath: /var/lib/cobalt/db
             # This name must match the volumes.name for shuffler-key-storage
             # below.
          - name: shuffler-key-storage
            mountPath: /var/lib/cobalt/key
            readOnly: true
      volumes:
        - name: shuffler-persistent-storage
          gcePersistentDisk:
            # The name of a GCE persistent disk that has already been created.
            pdName: $$GCE_PERSISTENT_DISK_NAME$$
            fsType: ext4
        - name: shuffler-key-storage
          secret:
            secretName: $$SHUFFLER_PRIVATE_KEY_SECRET_NAME$$
        - name: shuffler-certificate-storage
          secret:
            secretName: $$SHUFFLER_CERTIFICATE_SECRET_NAME$$
---
# The defintion of the Service
apiVersion: v1
kind: Service
metadata:
  name: shuffler
spec:
  ports:
    # Requests to this port are forwarded directly to the Shuffler
    # implementation on port 5000. This will be deleted after all clients have
    # been moved over to accessing the Shuffler through Cloud Endpoints.
  - port: 5001
    # The port which the Shuffler implementation exposes within the cluster.
    # This must match the value passed to the implementation in the "-port" flag
    # above and the value passed to the Endpoints process in the the "-a" flag
    # above and the value used in Shuffler's Dockerfile.
    targetPort: 5000
    protocol: TCP
    name: shuffler-http2
    # Requests to this port are forwarded to the Endpoints
    # implementation on port 8000.
  - port: 8001
    # The port which the Endpoint implementation exposes within the cluster.
    # This must match the value passed to the Endpoints process in the '-P' flag
    # above.
    targetPort: 8000
    protocol: TCP
    name: endpoint-http2
    # Requests to this port are forwarded to the Endpoints implementation
    # on the same port. Requests made to this port protected by TLS.
    # All clients should access Shuffler via this port.
  - port: 443
    protocol: TCP
    name: endpoint-https
  selector:
    # This must match the metadata.labels section of the Deployment above.
    name: shuffler
  type: LoadBalancer
  loadBalancerIP: $$SHUFFLER_STATIC_IP_ADDRESS$$

